FROM node:18-alpine

WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install --only=production

COPY . .

RUN npm run build
RUN npm install -g serve
RUN npm install -g pm2

EXPOSE 3000

CMD ["pm2-runtime", "server.js"]